import { Rarity } from "../../gameConfig";

export interface DeathEffectDef {
    readonly type: "death_effect";
    name: string;
    rarity: Rarity;
    texture: string;
    particle: string;
    particleCount?: number;
    sound?: string;
    // For animated sprite effects (like black hole)
    isParticle?: boolean;
    sprites?: string[];
    animationSpeed?: number;
    animationScale?: number;
    // For particle effects with custom min/max particle counts
    minParticles?: number;
    maxParticles?: number;
    // Discord snowflake as a string - a JS number would lose precision.
    creatorDiscordId?: string;
}

export const DeathEffectDefs: Record<string, DeathEffectDef> = {
    death_none: {
        type: "death_effect",
        name: "No Effect",
        rarity: Rarity.Stock,
        texture: "loot-skull-death.img",
        particle: "deathSplash",
        particleCount: 0,
    },
    death_basic: {
        type: "death_effect",
        name: "Standard Death",
        rarity: Rarity.Stock,
        texture: "loot-basic-puff-death.img",
        particle: "deathSplash",
        particleCount: 10,
    },
    death_blood_explosion: {
        type: "death_effect",
        name: "Blood Explosion",
        rarity: Rarity.Epic,
        texture: "loot-blood-explosion.img",
        particle: "bloodExplosion",
        particleCount: 15,
        isParticle: false,
        sprites: [
            "part-blood-explosion-01.img",
            "part-blood-explosion-02.img",
            "part-blood-explosion-03.img",
            "part-blood-explosion-04.img",
            "part-blood-explosion-05.img",
            "part-blood-explosion-06.img",
            "part-blood-explosion-07.img",
            "part-blood-explosion-08.img",
            "part-blood-explosion-09.img",
            "part-blood-explosion-10.img",
        ],
        animationSpeed: 0.25,
        animationScale: 0.7,
    },
    death_confetti: {
        type: "death_effect",
        name: "Confetti",
        rarity: Rarity.Mythic,
        texture: "loot-confetti-death.img",
        particle: "confettiDeath",
        isParticle: true,
        minParticles: 150,
        maxParticles: 150,
    },
    death_sparkle: {
        type: "death_effect",
        name: "Mr Sparkles",
        rarity: Rarity.Mythic,
        texture: "loot-sparkly-death.img",
        particle: "sparklyDeath",
        isParticle: true,
        minParticles: 45,
        maxParticles: 55,
    },
    death_potato: {
        type: "death_effect",
        name: "Potato Blast",
        rarity: Rarity.Epic,
        texture: "loot-potato-blast-death.img",
        particle: "potatoBlastDeath",
        isParticle: true,
        minParticles: 45,
        maxParticles: 55,
    },
    death_toon_blast: {
        type: "death_effect",
        name: "Toon Blast",
        rarity: Rarity.Mythic,
        texture: "loot-explosive-death.img",
        particle: "explosiveDeath",
        isParticle: false,
        sprites: [
            "death-explosive-1.img",
            "death-explosive-2.img",
            "death-explosive-3.img",
            "death-explosive-4.img",
            "death-explosive-5.img",
            "death-explosive-6.img",
        ],
        animationSpeed: 0.2,
        animationScale: 1.3,
    },
    death_turkey_feathers: {
        type: "death_effect",
        name: "Turkey Feathers",
        rarity: Rarity.Rare,
        texture: "loot-perk-turkey_shoot.img",
        particle: "turkeyFeathersDeath",
        isParticle: true,
        minParticles: 30,
        maxParticles: 35,
    },
    death_cupid: {
        type: "death_effect",
        name: "Cupid Hearts",
        rarity: Rarity.Rare,
        texture: "loot-perk-cupid.img",
        particle: "cupidDeath",
        isParticle: true,
        minParticles: 30,
        maxParticles: 35,
    },
    death_black_hole: {
        type: "death_effect",
        name: "Black Hole",
        rarity: Rarity.Epic,
        texture: "loot-black-hole.img",
        particle: "blackHoleDeath",
        particleCount: 15,
        isParticle: false,
        sprites: [
            "part-black-hole-09.img",
            "part-black-hole-08.img",
            "part-black-hole-07.img",
            "part-black-hole-06.img",
            "part-black-hole-05.img",
            "part-black-hole-04.img",
            "part-black-hole-03.img",
            "part-black-hole-02.img",
            "part-black-hole-01.img",
        ],
        animationSpeed: 0.15,
        animationScale: 1.2,
    },
    death_pixel_explosion: { // above death effects
        type: "death_effect",
        name: "Pixel Explosion",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Epic,
        texture: "loot-pixel-explosion.img",
        particle: "pixelExplosionDeath",
        isParticle: false,
        sprites: [
            "pixel-explosion-01.img",
            "pixel-explosion-02.img",
            "pixel-explosion-03.img",
            "pixel-explosion-04.img",
            "pixel-explosion-05.img",
            "pixel-explosion-06.img",
            "pixel-explosion-07.img",
            "pixel-explosion-08.img",
            "pixel-explosion-09.img",
            "pixel-explosion-10.img",
        ],
        animationSpeed: 0.15,
        animationScale: 0.65,
    },
    death_pulse: { // above death effects
        type: "death_effect",
        name: "Pulse Death",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Epic,
        texture: "loot-pulse-death.img",
        particle: "pulseDeath",
        isParticle: false,
        sprites: [
            "pulse-death-01.img",
            "pulse-death-02.img",
            "pulse-death-03.img",
            "pulse-death-04.img",
            "pulse-death-05.img",
            "pulse-death-06.img",
            "pulse-death-07.img",
            "pulse-death-08.img",
        ],
        animationSpeed: 0.20,
        animationScale: 2.2,
    },
    death_smoke: { // above death effects
        type: "death_effect",
        name: "Smoke Death",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Epic,
        texture: "loot-smoke-death.img",
        particle: "smokeDeath",
        isParticle: false,
        sprites: [
            "smoke-death-01.img",
            "smoke-death-02.img",
            "smoke-death-03.img",
            "smoke-death-04.img",
            "smoke-death-05.img",
            "smoke-death-06.img",
            "smoke-death-07.img",
            "smoke-death-08.img",
            "smoke-death-09.img",
            "smoke-death-10.img",
            "smoke-death-11.img",
        ],
        animationSpeed: 0.35,
        animationScale: 0.65,
    
    },
    death_magic_spark: {
        type: "death_effect",
        name: "Magic Sparks",
        rarity: Rarity.Mythic,
        texture: "loot-magic-spark.img",
        particle: "magicSparkDeath",
        isParticle: true,
        minParticles: 30,
        maxParticles: 35,
    },
    death_touhou: { // above death effects
        type: "death_effect",
        name: "Touhou Death",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Mythic,
        texture: "loot-touhou-death.img",
        particle: "touhouDeath",
        isParticle: true,
        minParticles: 25,
        maxParticles: 30,
    },
    death_bubble: { // above death effects
        type: "death_effect",
        name: "Bubble Death",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Mythic,
        texture: "loot-bubble-death.img",
        particle: "bubbleDeath",
        isParticle: true,
        minParticles: 25,
        maxParticles: 30,
    },
    death_shattered_glass: { // above death effects
        type: "death_effect",
        name: "Shattered Glass",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Mythic,
        texture: "loot-shattered-glass-death.img",
        particle: "shatteredGlassDeath",
        isParticle: true,
        minParticles: 20,
        maxParticles: 25,
    },
    death_xp_orb: { // above death effects
        type: "death_effect",
        name: "XP Orb",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Mythic,
        texture: "loot-xp-orb-death.img",
        particle: "xpOrbDeath",
        isParticle: true,
        minParticles: 10,
        maxParticles: 30,
    },
    death_alphabet_soup: { // above death effects
        type: "death_effect",
        name: "Alphabet Soup",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Mythic,
        texture: "loot-alphabet-soup-death.img",
        particle: "alphabetSoupDeath",
        isParticle: true,
        minParticles: 30,
        maxParticles: 40,
    },
    death_drop_cellphone: { // above death effects
        type: "death_effect",
        name: "Drop Cellphone",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Mythic,
        texture: "loot-drop-cellphone.img",
        particle: "dropCellphoneDeath",
        isParticle: true,
        minParticles: 1,
        maxParticles: 1,
    },
    death_billionaire: {
        type: "death_effect",
        name: "Billionaire",
        rarity: Rarity.Mythic,
        texture: "loot-billionaire-death.img",
        particle: "billionaireDeath",
        isParticle: true,
        minParticles: 30,
        maxParticles: 35,
    },
};
